name: Update Filter Lists

on:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: production

jobs:
  compare-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Restore last SHA cache
        id: cache-sha
        uses: actions/cache/restore@v5
        with:
          path: last_sha.txt
          key: file-sha-${{ github.run_id }}
          restore-keys: |
            file-sha-

      - name: Get latest SHA and compare
        run: |
          RESPONSE=$(curl -s "https://api.github.com/repos/Zziniswell/Adguard-gallery-filter/contents/DNS.txt")
          LATEST_SHA=$(echo "$RESPONSE" | jq -r '.sha')
          
          if [ -f last_sha.txt ]; then
            OLD_SHA=$(cat last_sha.txt)
          else
            OLD_SHA="none"
          fi

          echo "OLD_SHA: $OLD_SHA"
          echo "LATEST_SHA: $LATEST_SHA"

          echo "$LATEST_SHA" > last_sha.txt
          
          if [ "$OLD_SHA" = "none" ]; then
            echo "This is the first run."
            exit 0 
          elif [ "$OLD_SHA" != "$LATEST_SHA" ]; then
            echo "The file has changed!"
            exit 1
          else
            echo "No changes."
            exit 0
          fi

      - name: Save new SHA to cache
        if: always()
        uses: actions/cache/save@v5
        with:
          path: last_sha.txt
          key: file-sha-${{ github.run_id }}
          
  cgps:
    runs-on: ubuntu-latest
    needs: compare-hash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: "mrrfv/cloudflare-gateway-pihole-scripts"
          ref: "v1"

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Install npm dependencies
        run: npm ci

      - name: Download allowlists
        run: npm run download:allowlist
        env:
          ALLOWLIST_URLS: ${{ vars.ALLOWLIST_URLS }}

      - name: Download blocklists
        run: npm run download:blocklist
        env:
          BLOCKLIST_URLS: ${{ vars.BLOCKLIST_URLS }}

      - name: Create or update rules and lists
        run: npm run cloudflare-create
        env:
          BLOCK_PAGE_ENABLED: ${{ vars.BLOCK_PAGE_ENABLED }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_LIST_ITEM_LIMIT: ${{ secrets.CLOUDFLARE_LIST_ITEM_LIMIT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send ping request
        if: env.PING_URL != ''
        run: |
          curl "${{ env.PING_URL }}"
        env:
          PING_URL: ${{ secrets.PING_URL }}

  keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
